# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6837232fcf9d6b5caaacfec4652e84c2528cd79cb2376a5f3ed8f13f2274f4713a64ac183e7dca6dcdff65c121f772ee4d8ec5dc50c0d847c9f77815ae2ab98f

test:
  secret_key_base: eb2906d550b9213b62936a92b2b8ba7cf46a969e806548ccc29ff139799ac0aa744fdfbc8b1ac42cb33ea5191271329a0ccafd334340ffaad0cd259444b23ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
